(function(){'use strict';
var f="object"===typeof __ScalaJSEnv&&__ScalaJSEnv?__ScalaJSEnv:{},k="object"===typeof f.global&&f.global?f.global:"object"===typeof global&&global&&global.Object===Object?global:this;f.global=k;var l="object"===typeof f.exportsNamespace&&f.exportsNamespace?f.exportsNamespace:k;f.exportsNamespace=l;k.Object.freeze(f);var n={envInfo:f,semantics:{asInstanceOfs:2,moduleInit:2,strictFloats:!1,productionMode:!0},assumingES6:!1,linkerVersion:"0.6.8"};k.Object.freeze(n);k.Object.freeze(n.semantics);
var q=k.Math.imul||function(a,b){var c=a&65535,d=b&65535;return c*d+((a>>>16&65535)*d+c*(b>>>16&65535)<<16>>>0)|0},r=k.Math.clz32||function(a){if(0===a)return 32;var b=1;0===(a&4294901760)&&(a<<=16,b+=16);0===(a&4278190080)&&(a<<=8,b+=8);0===(a&4026531840)&&(a<<=4,b+=4);0===(a&3221225472)&&(a<<=2,b+=2);return b+(a>>31)},s=0,t=k.WeakMap?new k.WeakMap:null;function u(a){return function(b,c){return!(!b||!b.a||b.a.n!==c||b.a.l!==a)}}function aa(a){for(var b in a)return b}
function v(a,b,c){var d=new a.D(b[c]);if(c<b.length-1){a=a.o;c+=1;for(var e=d.B,g=0;g<e.length;g++)e[g]=v(a,b,c)}return d}function ba(a){switch(typeof a){case "string":return w(x);case "number":var b=a|0;return b===a?b<<24>>24===b&&1/b!==1/-0?w(z):b<<16>>16===b&&1/b!==1/-0?w(A):w(B):"number"===typeof a?w(C):w(D);case "boolean":return w(E);case "undefined":return w(F);default:return null===a?a.ha():a&&a.a&&a.a.i.z?w(G):a&&a.a?w(a.a):null}}
function H(a){switch(typeof a){case "string":I||(I=(new J).g());for(var b=0,c=1,d=-1+(a.length|0)|0;0<=d;)b=b+q(65535&(a.charCodeAt(d)|0),c)|0,c=q(31,c),d=-1+d|0;return b;case "number":K||(K=(new L).g());b=K;c=a|0;if(c===a&&-Infinity!==1/a)b=c;else{if(b.j)b.E[0]=a,b=M(N(O(b.t[b.F]|0)),ca((new P).d(-1,0),O(b.t[b.G]|0)));else{if(a!==a)b=!1,a=2047,c=+k.Math.pow(2,51);else if(Infinity===a||-Infinity===a)b=0>a,a=2047,c=0;else if(0===a)b=-Infinity===1/a,c=a=0;else if(d=(b=0>a)?-a:a,d>=+k.Math.pow(2,-1022)){a=
+k.Math.pow(2,52);var c=+k.Math.log(d)/0.6931471805599453,c=+k.Math.floor(c)|0,c=1023>c?c:1023,e=d/+k.Math.pow(2,c)*a,d=+k.Math.floor(e),e=e-d,d=0.5>e?d:0.5<e?1+d:0!==d%2?1+d:d;2<=d/a&&(c=1+c|0,d=1);1023<c?(c=2047,d=0):(c=1023+c|0,d-=a);a=c;c=d}else a=d/+k.Math.pow(2,-1074),c=+k.Math.floor(a),d=a-c,a=0,c=0.5>d?c:0.5<d?1+c:0!==c%2?1+c:c;c=+c;d=c|0;b=M(N(O((b?-2147483648:0)|(a|0)<<20|c/4294967296|0)),ca((new P).d(-1,0),O(d)))}b=b.e^b.f}return b;case "boolean":return a?1231:1237;case "undefined":return 0;
default:return a&&a.a||null===a?a.y():null===t?42:ea(a)}}function fa(a,b){for(var c=k.Object.getPrototypeOf,d=k.Object.getOwnPropertyDescriptor,e=c(a);null!==e;){var g=d(e,b);if(void 0!==g)return g;e=c(e)}}function ga(a,b,c){a=fa(a,c);if(void 0!==a)return c=a.get,void 0!==c?c.call(b):a.value}function ha(a,b,c,d){a=fa(a,c);if(void 0!==a&&(a=a.set,void 0!==a)){a.call(b,d);return}throw new k.TypeError("super has no setter '"+c+"'.");}
var ea=null!==t?function(a){switch(typeof a){case "string":case "number":case "boolean":case "undefined":return H(a);default:if(null===a)return 0;var b=t.get(a);void 0===b&&(s=b=s+1|0,t.set(a,b));return b}}:function(a){if(a&&a.a){var b=a.$idHashCode$0;if(void 0!==b)return b;if(k.Object.isSealed(a))return 42;s=b=s+1|0;return a.$idHashCode$0=b}return null===a?0:H(a)};this.__ScalaJSExportsNamespace=l;
function Q(){this.u=this.D=void 0;this.l=this.o=this.i=null;this.n=0;this.C=null;this.s="";this.c=this.q=this.r=void 0;this.name="";this.isRawJSType=this.isArrayClass=this.isInterface=this.isPrimitive=!1;this.isInstance=void 0}function R(a,b,c){var d=new Q;d.i={};d.o=null;d.C=a;d.s=b;d.c=function(){return!1};d.name=c;d.isPrimitive=!0;d.isInstance=function(){return!1};return d}
function S(a,b,c,d,e,g,p){var h=new Q,m=aa(a);g=g||function(a){return!!(a&&a.a&&a.a.i[m])};p=p||function(a,b){return!!(a&&a.a&&a.a.n===b&&a.a.l.i[m])};h.u=e;h.i=c;h.s="L"+b+";";h.c=p;h.name=b;h.isInterface=!1;h.isRawJSType=!!d;h.isInstance=g;return h}
function ia(a){function b(a){if("number"===typeof a){this.B=Array(a);for(var b=0;b<a;b++)this.B[b]=e}else this.B=a}var c=new Q,d=a.C,e="longZero"==d?ja().w:d;b.prototype=new T;b.prototype.a=c;var d="["+a.s,g=a.l||a,p=a.n+1;c.D=b;c.u=ka;c.i={b:1,ja:1,v:1};c.o=a;c.l=g;c.n=p;c.C=null;c.s=d;c.r=void 0;c.q=void 0;c.c=void 0;c.name=d;c.isPrimitive=!1;c.isInterface=!1;c.isArrayClass=!0;c.isInstance=function(a){return g.c(a,p)};return c}function w(a){if(!a.r){var b=new U;b.p=a;a.r=b}return a.r}
Q.prototype.getFakeInstance=function(){return this===x?"some string":this===E?!1:this===z||this===A||this===B||this===C||this===D?0:this===G?ja().w:this===F?void 0:{a:this}};Q.prototype.getSuperclass=function(){return this.u?w(this.u):null};Q.prototype.getComponentType=function(){return this.o?w(this.o):null};Q.prototype.newArrayOfThisClass=function(a){for(var b=this,c=0;c<a.length;c++)b.q||(b.q=ia(b)),b=b.q;return v(b,a,0)};
var la=R(!1,"Z","boolean"),ma=R(0,"C","char"),na=R(0,"B","byte"),oa=R(0,"S","short"),pa=R(0,"I","int"),ra=R("longZero","J","long"),sa=R(0,"F","float"),ta=R(0,"D","double");la.c=u(la);ma.c=u(ma);na.c=u(na);oa.c=u(oa);pa.c=u(pa);ra.c=u(ra);sa.c=u(sa);ta.c=u(ta);function V(){}function T(){}T.prototype=V.prototype;V.prototype.g=function(){return this};V.prototype.A=function(){var a;a=ba(this).p.name;var b=(+(this.y()>>>0)).toString(16);return a+"@"+b};V.prototype.y=function(){return ea(this)};V.prototype.toString=function(){return this.A()};var ka=S({b:0},"java.lang.Object",{b:1},void 0,void 0,function(a){return null!==a},function(a,b){var c=a&&a.a;if(c){var d=c.n||0;return!(d<b)&&(d>b||!c.l.isPrimitive)}return!1});V.prototype.a=ka;function W(){}
W.prototype=new T;W.prototype.constructor=W;W.prototype.g=function(){return this};W.prototype.factorial=function(a){a:{var b=a|0;a=1;for(;;)switch(b){case 1:break a;default:a=q(a,b),b=-1+b|0}a=void 0}return a};W.prototype.a=S({H:0},"omega.OmegaJS$",{H:1,b:1});var X=void 0;l.omega=l.omega||{};l.omega.OmegaJS=function(){X||(X=(new W).g());return X};function U(){this.p=null}U.prototype=new T;U.prototype.constructor=U;
U.prototype.A=function(){return(this.p.isInterface?"interface ":this.p.isPrimitive?"":"class ")+this.p.name};U.prototype.a=S({Q:0},"java.lang.Class",{Q:1,b:1});function Y(){}Y.prototype=new T;Y.prototype.constructor=Y;function va(){}va.prototype=Y.prototype;function L(){this.j=!1;this.E=this.N=this.t=this.m=null;this.x=!1;this.G=this.F=0}L.prototype=new T;L.prototype.constructor=L;
L.prototype.g=function(){K=this;this.m=(this.j=!!(k.ArrayBuffer&&k.Int32Array&&k.Float32Array&&k.Float64Array))?new k.ArrayBuffer(8):null;this.t=this.j?new k.Int32Array(this.m,0,2):null;this.N=this.j?new k.Float32Array(this.m,0,2):null;this.E=this.j?new k.Float64Array(this.m,0,1):null;if(this.j)this.t[0]=16909060,a=1===((new k.Int8Array(this.m,0,8))[0]|0);else var a=!0;this.F=(this.x=a)?0:1;this.G=this.x?1:0;return this};L.prototype.a=S({W:0},"scala.scalajs.runtime.Bits$",{W:1,b:1});var K=void 0;
function J(){this.ca=null;this.ga=!1}J.prototype=new T;J.prototype.constructor=J;J.prototype.g=function(){return this};J.prototype.a=S({Y:0},"scala.scalajs.runtime.RuntimeString$",{Y:1,b:1});
var I=void 0,F=S({Z:0},"scala.runtime.BoxedUnit",{Z:1,b:1},void 0,void 0,function(a){return void 0===a}),E=S({O:0},"java.lang.Boolean",{O:1,b:1,h:1},void 0,void 0,function(a){return"boolean"===typeof a}),z=S({P:0},"java.lang.Byte",{P:1,k:1,b:1,h:1},void 0,void 0,function(a){return a<<24>>24===a&&1/a!==1/-0}),D=S({R:0},"java.lang.Double",{R:1,k:1,b:1,h:1},void 0,void 0,function(a){return"number"===typeof a}),C=S({S:0},"java.lang.Float",{S:1,k:1,b:1,h:1},void 0,void 0,function(a){return"number"===typeof a}),
B=S({T:0},"java.lang.Integer",{T:1,k:1,b:1,h:1},void 0,void 0,function(a){return(a|0)===a&&1/a!==1/-0}),G=S({U:0},"java.lang.Long",{U:1,k:1,b:1,h:1},void 0,void 0,function(a){return!!(a&&a.a&&a.a.i.z)}),A=S({V:0},"java.lang.Short",{V:1,k:1,b:1,h:1},void 0,void 0,function(a){return a<<16>>16===a&&1/a!==1/-0});function Z(){this.$=this.ba=this.aa=this.fa=this.ea=this.da=0;this.I=this.J=this.K=this.L=this.w=null}Z.prototype=new T;Z.prototype.constructor=Z;
Z.prototype.g=function(){$=this;this.w=(new P).d(0,0);this.L=(new P).d(1,0);this.K=(new P).d(-1,-1);this.J=(new P).d(0,-2147483648);this.I=(new P).d(-1,2147483647);return this};Z.prototype.a=S({X:0},"scala.scalajs.runtime.RuntimeLong$",{X:1,b:1,ka:1,v:1});var $=void 0;function ja(){$||($=(new Z).g());return $}var x=S({M:0},"java.lang.String",{M:1,b:1,v:1,ia:1,h:1},void 0,void 0,function(a){return"string"===typeof a});function P(){this.f=this.e=0}P.prototype=new va;P.prototype.constructor=P;
function M(a,b){return(new P).d(a.e|b.e,a.f|b.f)}P.prototype.A=function(){var a=this.e,b=this.f;return b===a>>31?""+a:0>b?"-"+wa(-a|0,0!==a?~b:-b|0):wa(a,b)};P.prototype.d=function(a,b){this.e=a;this.f=b;return this};function ca(a,b){return(new P).d(a.e&b.e,a.f&b.f)}function N(a){return(new P).d(0,a.e<<32)}function O(a){var b=new P;P.prototype.d.call(b,a,a>>31);return b}P.prototype.y=function(){return this.e^this.f};
function wa(a,b){if(0===(-2097152&b))return""+(4294967296*b+ +(a>>>0));var c,d=(32+r(1E9)|0)-(0!==b?r(b):32+r(a)|0)|0,e=d;0===e?(c=1E9,e=0):32>e?(c=1E9<<e,e=1E9>>>(-e|0)|0|0<<e):(c=0,e=1E9<<e);for(var g=c,p=e,h=a,m=b,e=c=0;0<=d&&0!==(-2097152&m);){var y=h,da=m,ua=g,qa=p;if(da===qa?(-2147483648^y)>=(-2147483648^ua):(-2147483648^da)>=(-2147483648^qa))y=h,h=y-g|0,m=(m-p|0)+((-2147483648^y)<(-2147483648^h)?-1:0)|0,32>d?c|=1<<d:e|=1<<d;d=-1+d|0;y=p>>>1|0;g=g>>>1|0|p<<-1;p=y}d=m;if(0===d?-1147483648<=(-2147483648^
h):-2147483648<=(-2147483648^d))d=4294967296*m+ +(h>>>0),g=d/1E9,h=c,c=m=h+(g|0)|0,e=(e+(g/4294967296|0)|0)+((-2147483648^m)<(-2147483648^h)?1:0)|0,d%=1E9,h=d|0,m=d/4294967296|0;c=[c,e,h,m];e=""+(c["2"]|0);return""+(4294967296*(c["1"]|0)+ +((c["0"]|0)>>>0))+"000000000".substring(e.length|0)+e}P.prototype.a=S({z:0},"scala.scalajs.runtime.RuntimeLong",{z:1,k:1,b:1,v:1,h:1});
}).call(this);
//# sourceMappingURL=javascript-opt.js.map
